TARGET = game.exe

CFLAGS += -I./
CFLAGS += -I/usr/include/SDL2/

LDFLAGS += -lSDL2
LDFLAGS += -lSDL2_image-2.0
LDFLAGS += -lSDL2_ttf

SRC = 
SRC += GlobalConfig.cpp
SRC += Screen.cpp
SRC += Base.cpp
SRC += Background.cpp

SRC += L08.Geometry.cpp
SRC += L10.ColorKey.cpp
SRC += L11.Sprite.cpp
SRC += L12.ColorModulation.cpp
SRC += L14.AnimatedSprites.cpp
SRC += L16.TTFonts.cpp
SRC += L22.Timing.cpp
SRC += L24.FrameRate.cpp

SRC += main.cpp

include Makefile.include.app
