TARGET = game.exe

CFLAGS += -I./
CFLAGS += -I/usr/include/SDL2/

LDFLAGS += -lSDL2
LDFLAGS += -lSDL2_image-2.0

SRC = 
SRC += main.cpp
SRC += Screen.cpp
SRC += Background.cpp

include Makefile.include.app
