TARGET = game.exe

CFLAGS += -I./
CFLAGS += -I/usr/include/SDL2/

LDFLAGS += -lSDL2
LDFLAGS += -lSDL2_image-2.0

SRC = 
SRC += GlobalConfig.cpp
SRC += Screen.cpp
SRC += Base.cpp
SRC += Background.cpp
SRC += Geometry.cpp
SRC += ColorKey.cpp
SRC += Sprite.cpp
SRC += ColorModulation.cpp
SRC += main.cpp

include Makefile.include.app
